config/routes.rb
Rails.application.routes.draw do
  resources :lotes
  resources :details
  resources :bills
  resources :clients
  resources :articles
  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lote.rb
class Lote < ApplicationRecord
	belongs_to :article
end

app/controllers/lotes_controller.rb
class LotesController < ApplicationController
  before_action :set_lote, only: [:show, :edit, :update, :destroy]

  # GET /lotes
  # GET /lotes.json
  def index
    @lotes = Lote.all
  end

  # GET /lotes/1
  # GET /lotes/1.json
  def show
  end

  # GET /lotes/new
  def new
    @lote = Lote.new
  end

  # GET /lotes/1/edit
  def edit
  end

  # POST /lotes
  # POST /lotes.json
  def create
    @lote = Lote.new(lote_params)

    respond_to do |format|
      if @lote.save
        format.html { redirect_to @lote, notice: 'Lote was successfully created.' }
        format.json { render :show, status: :created, location: @lote }
      else
        format.html { render :new }
        format.json { render json: @lote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lotes/1
  # PATCH/PUT /lotes/1.json
  def update
    respond_to do |format|
      if @lote.update(lote_params)
        format.html { redirect_to @lote, notice: 'Lote was successfully updated.' }
        format.json { render :show, status: :ok, location: @lote }
      else
        format.html { render :edit }
        format.json { render json: @lote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lotes/1
  # DELETE /lotes/1.json
  def destroy
    @lote.destroy
    respond_to do |format|
      format.html { redirect_to lotes_url, notice: 'Lote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lote
      @lote = Lote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lote_params
      params.require(:lote).permit(:cost, :quantity)
    end
end

app/helpers/lotes_helper.rb
module LotesHelper
end

app/views/lotes/_form.html.erb
<%= form_for(lote) do |f| %>
  <% if lote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lote.errors.count, "error") %> prohibited this lote from being saved:</h2>

      <ul>
      <% lote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lotes/edit.html.erb
<h1>Editing Lote</h1>

<%= render 'form', lote: @lote %>

<%= link_to 'Show', @lote %> |
<%= link_to 'Back', lotes_path %>

app/views/lotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lotes</h1>

<table>
  <thead>
    <tr>
      <th>Cost</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lotes.each do |lote| %>
      <tr>
        <td><%= lote.cost %></td>
        <td><%= lote.quantity %></td>
        <td><%= link_to 'Show', lote %></td>
        <td><%= link_to 'Edit', edit_lote_path(lote) %></td>
        <td><%= link_to 'Destroy', lote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lote', new_lote_path %>

app/views/lotes/new.html.erb
<h1>New Lote</h1>

<%= render 'form', lote: @lote %>

<%= link_to 'Back', lotes_path %>

app/views/lotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost:</strong>
  <%= @lote.cost %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @lote.quantity %>
</p>

<%= link_to 'Edit', edit_lote_path(@lote) %> |
<%= link_to 'Back', lotes_path %>